# For Picking Jib Maven Pluging (JMP) configuration -----------------------------------------
# JMP is a google pluging for docker image lifecycle Managment :
# - Create docker images without the need of any local docker installation  
# - Push directly the created images to the Docker Registry of our choice (Docker hub, ...) 

container:
  mainClass: ma.itroad.configserver.ConfigServerApplication
  port.tcp: 8062
  jvm:
    jdk.image.source: adoptopenjdk/openjdk11:x86_64-alpine-jre-11.0.5_10
    flag:
      param1: -Xms512m
      param2: -Xdebug  
  image.target.url.base: registry.hub.docker.com/ramitroad2021/ram
